// @generated by robonix-codegen (--contracts). Source: proto import closure for `robonix_contracts.proto`.
// Do not edit by hand.
// `tonic::include_proto!` order matches prost `super::` sibling resolution.
// Most generated types are unused in any single binary.
// (Suppress dead_code on the `robonix-interfaces` crate — not `#![allow]` here: included via `include!`.)

pub mod audio {
    tonic::include_proto!("robonix.audio");
}

pub mod asr {
    tonic::include_proto!("robonix.asr");
}

pub mod builtin_interfaces {
    tonic::include_proto!("robonix.builtin_interfaces");
}

pub mod std_msgs {
    tonic::include_proto!("robonix.std_msgs");
}

pub mod geometry_msgs {
    tonic::include_proto!("robonix.geometry_msgs");
}

pub mod sensor_msgs {
    tonic::include_proto!("robonix.sensor_msgs");
}

pub mod camera {
    tonic::include_proto!("robonix.camera");
}

pub mod chassis {
    tonic::include_proto!("robonix.chassis");
}

pub mod pilot {
    tonic::include_proto!("robonix.pilot");
}

pub mod executor {
    tonic::include_proto!("robonix.executor");
}

pub mod lidar {
    tonic::include_proto!("robonix.lidar");
}

pub mod lifecycle {
    tonic::include_proto!("robonix.lifecycle");
}

pub mod memory {
    tonic::include_proto!("robonix.memory");
}

pub mod nav_msgs {
    tonic::include_proto!("robonix.nav_msgs");
}

pub mod navigation {
    tonic::include_proto!("robonix.navigation");
}

pub mod semantic_map {
    tonic::include_proto!("robonix.semantic_map");
}

pub mod slam {
    tonic::include_proto!("robonix.slam");
}

pub mod speech {
    tonic::include_proto!("robonix.speech");
}

pub mod tts {
    tonic::include_proto!("robonix.tts");
}

pub mod contracts {
    tonic::include_proto!("robonix.contracts");
}

