# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: actionlib_msgs.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'actionlib_msgs.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import builtin_interfaces_pb2 as builtin__interfaces__pb2
import std_msgs_pb2 as std__msgs__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x61\x63tionlib_msgs.proto\x12\x16robonix.actionlib_msgs\x1a\x18\x62uiltin_interfaces.proto\x1a\x0estd_msgs.proto\"E\n\x06GoalID\x12/\n\x05stamp\x18\x01 \x01(\x0b\x32 .robonix.builtin_interfaces.Time\x12\n\n\x02id\x18\x02 \x01(\t\"[\n\nGoalStatus\x12/\n\x07goal_id\x18\x01 \x01(\x0b\x32\x1e.robonix.actionlib_msgs.GoalID\x12\x0e\n\x06status\x18\x02 \x01(\r\x12\x0c\n\x04text\x18\x03 \x01(\t\"t\n\x0fGoalStatusArray\x12(\n\x06header\x18\x01 \x01(\x0b\x32\x18.robonix.std_msgs.Header\x12\x37\n\x0bstatus_list\x18\x02 \x03(\x0b\x32\".robonix.actionlib_msgs.GoalStatusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'actionlib_msgs_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GOALID']._serialized_start=90
  _globals['_GOALID']._serialized_end=159
  _globals['_GOALSTATUS']._serialized_start=161
  _globals['_GOALSTATUS']._serialized_end=252
  _globals['_GOALSTATUSARRAY']._serialized_start=254
  _globals['_GOALSTATUSARRAY']._serialized_end=370
# @@protoc_insertion_point(module_scope)
