# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: asr.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'asr.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import audio_pb2 as audio__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tasr.proto\x12\x0brobonix.asr\x1a\x0b\x61udio.proto\"9\n\rAsrAudioChunk\x12(\n\x05\x63hunk\x18\x01 \x01(\x0b\x32\x19.robonix.audio.AudioChunk\"\x7f\n\x14RecognizeStreamEvent\x12\x12\n\nevent_type\x18\x01 \x01(\r\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x12\n\nconfidence\x18\x03 \x01(\x02\x12\x10\n\x08language\x18\x04 \x01(\t\x12\x10\n\x08is_final\x18\x05 \x01(\x08\x12\r\n\x05\x65rror\x18\x06 \x01(\t\"c\n\x11Recognize_Request\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\x12\x10\n\x08\x65ncoding\x18\x02 \x01(\t\x12\x16\n\x0esample_rate_hz\x18\x03 \x01(\r\x12\x10\n\x08language\x18\x04 \x01(\t\"E\n\x12Recognize_Response\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\r\n\x05\x65rror\x18\x03 \x01(\t\"]\n\x17RecognizeStream_Request\x12\x30\n\x0c\x61udio_config\x18\x01 \x01(\x0b\x32\x1a.robonix.audio.AudioConfig\x12\x10\n\x08language\x18\x02 \x01(\t\"L\n\x18RecognizeStream_Response\x12\x30\n\x05\x65vent\x18\x01 \x01(\x0b\x32!.robonix.asr.RecognizeStreamEventb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'asr_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ASRAUDIOCHUNK']._serialized_start=39
  _globals['_ASRAUDIOCHUNK']._serialized_end=96
  _globals['_RECOGNIZESTREAMEVENT']._serialized_start=98
  _globals['_RECOGNIZESTREAMEVENT']._serialized_end=225
  _globals['_RECOGNIZE_REQUEST']._serialized_start=227
  _globals['_RECOGNIZE_REQUEST']._serialized_end=326
  _globals['_RECOGNIZE_RESPONSE']._serialized_start=328
  _globals['_RECOGNIZE_RESPONSE']._serialized_end=397
  _globals['_RECOGNIZESTREAM_REQUEST']._serialized_start=399
  _globals['_RECOGNIZESTREAM_REQUEST']._serialized_end=492
  _globals['_RECOGNIZESTREAM_RESPONSE']._serialized_start=494
  _globals['_RECOGNIZESTREAM_RESPONSE']._serialized_end=570
# @@protoc_insertion_point(module_scope)
