# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import atlas_pb2 as atlas__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in atlas_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AtlasStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterCapability = channel.unary_unary(
                '/robonix.atlas.Atlas/RegisterCapability',
                request_serializer=atlas__pb2.RegisterCapabilityRequest.SerializeToString,
                response_deserializer=atlas__pb2.RegisterCapabilityResponse.FromString,
                _registered_method=True)
        self.UnregisterCapability = channel.unary_unary(
                '/robonix.atlas.Atlas/UnregisterCapability',
                request_serializer=atlas__pb2.UnregisterCapabilityRequest.SerializeToString,
                response_deserializer=atlas__pb2.UnregisterCapabilityResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/robonix.atlas.Atlas/Heartbeat',
                request_serializer=atlas__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=atlas__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.DeclareInterface = channel.unary_unary(
                '/robonix.atlas.Atlas/DeclareInterface',
                request_serializer=atlas__pb2.DeclareInterfaceRequest.SerializeToString,
                response_deserializer=atlas__pb2.DeclareInterfaceResponse.FromString,
                _registered_method=True)
        self.QueryCapabilities = channel.unary_unary(
                '/robonix.atlas.Atlas/QueryCapabilities',
                request_serializer=atlas__pb2.QueryCapabilitiesRequest.SerializeToString,
                response_deserializer=atlas__pb2.QueryCapabilitiesResponse.FromString,
                _registered_method=True)
        self.QueryCapabilityMd = channel.unary_unary(
                '/robonix.atlas.Atlas/QueryCapabilityMd',
                request_serializer=atlas__pb2.QueryCapabilityMdRequest.SerializeToString,
                response_deserializer=atlas__pb2.QueryCapabilityMdResponse.FromString,
                _registered_method=True)
        self.ConnectCapability = channel.unary_unary(
                '/robonix.atlas.Atlas/ConnectCapability',
                request_serializer=atlas__pb2.ConnectCapabilityRequest.SerializeToString,
                response_deserializer=atlas__pb2.ConnectCapabilityResponse.FromString,
                _registered_method=True)
        self.DisconnectCapability = channel.unary_unary(
                '/robonix.atlas.Atlas/DisconnectCapability',
                request_serializer=atlas__pb2.DisconnectCapabilityRequest.SerializeToString,
                response_deserializer=atlas__pb2.DisconnectCapabilityResponse.FromString,
                _registered_method=True)
        self.QueryContract = channel.unary_unary(
                '/robonix.atlas.Atlas/QueryContract',
                request_serializer=atlas__pb2.QueryContractRequest.SerializeToString,
                response_deserializer=atlas__pb2.QueryContractResponse.FromString,
                _registered_method=True)
        self.ListContracts = channel.unary_unary(
                '/robonix.atlas.Atlas/ListContracts',
                request_serializer=atlas__pb2.ListContractsRequest.SerializeToString,
                response_deserializer=atlas__pb2.ListContractsResponse.FromString,
                _registered_method=True)
        self.InspectAtlas = channel.unary_unary(
                '/robonix.atlas.Atlas/InspectAtlas',
                request_serializer=atlas__pb2.InspectAtlasRequest.SerializeToString,
                response_deserializer=atlas__pb2.InspectAtlasResponse.FromString,
                _registered_method=True)


class AtlasServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterCapability(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnregisterCapability(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeclareInterface(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryCapabilities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryCapabilityMd(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConnectCapability(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisconnectCapability(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryContract(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListContracts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InspectAtlas(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AtlasServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterCapability': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterCapability,
                    request_deserializer=atlas__pb2.RegisterCapabilityRequest.FromString,
                    response_serializer=atlas__pb2.RegisterCapabilityResponse.SerializeToString,
            ),
            'UnregisterCapability': grpc.unary_unary_rpc_method_handler(
                    servicer.UnregisterCapability,
                    request_deserializer=atlas__pb2.UnregisterCapabilityRequest.FromString,
                    response_serializer=atlas__pb2.UnregisterCapabilityResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=atlas__pb2.HeartbeatRequest.FromString,
                    response_serializer=atlas__pb2.HeartbeatResponse.SerializeToString,
            ),
            'DeclareInterface': grpc.unary_unary_rpc_method_handler(
                    servicer.DeclareInterface,
                    request_deserializer=atlas__pb2.DeclareInterfaceRequest.FromString,
                    response_serializer=atlas__pb2.DeclareInterfaceResponse.SerializeToString,
            ),
            'QueryCapabilities': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryCapabilities,
                    request_deserializer=atlas__pb2.QueryCapabilitiesRequest.FromString,
                    response_serializer=atlas__pb2.QueryCapabilitiesResponse.SerializeToString,
            ),
            'QueryCapabilityMd': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryCapabilityMd,
                    request_deserializer=atlas__pb2.QueryCapabilityMdRequest.FromString,
                    response_serializer=atlas__pb2.QueryCapabilityMdResponse.SerializeToString,
            ),
            'ConnectCapability': grpc.unary_unary_rpc_method_handler(
                    servicer.ConnectCapability,
                    request_deserializer=atlas__pb2.ConnectCapabilityRequest.FromString,
                    response_serializer=atlas__pb2.ConnectCapabilityResponse.SerializeToString,
            ),
            'DisconnectCapability': grpc.unary_unary_rpc_method_handler(
                    servicer.DisconnectCapability,
                    request_deserializer=atlas__pb2.DisconnectCapabilityRequest.FromString,
                    response_serializer=atlas__pb2.DisconnectCapabilityResponse.SerializeToString,
            ),
            'QueryContract': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryContract,
                    request_deserializer=atlas__pb2.QueryContractRequest.FromString,
                    response_serializer=atlas__pb2.QueryContractResponse.SerializeToString,
            ),
            'ListContracts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListContracts,
                    request_deserializer=atlas__pb2.ListContractsRequest.FromString,
                    response_serializer=atlas__pb2.ListContractsResponse.SerializeToString,
            ),
            'InspectAtlas': grpc.unary_unary_rpc_method_handler(
                    servicer.InspectAtlas,
                    request_deserializer=atlas__pb2.InspectAtlasRequest.FromString,
                    response_serializer=atlas__pb2.InspectAtlasResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'robonix.atlas.Atlas', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('robonix.atlas.Atlas', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Atlas(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterCapability(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robonix.atlas.Atlas/RegisterCapability',
            atlas__pb2.RegisterCapabilityRequest.SerializeToString,
            atlas__pb2.RegisterCapabilityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnregisterCapability(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robonix.atlas.Atlas/UnregisterCapability',
            atlas__pb2.UnregisterCapabilityRequest.SerializeToString,
            atlas__pb2.UnregisterCapabilityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robonix.atlas.Atlas/Heartbeat',
            atlas__pb2.HeartbeatRequest.SerializeToString,
            atlas__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeclareInterface(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robonix.atlas.Atlas/DeclareInterface',
            atlas__pb2.DeclareInterfaceRequest.SerializeToString,
            atlas__pb2.DeclareInterfaceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryCapabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robonix.atlas.Atlas/QueryCapabilities',
            atlas__pb2.QueryCapabilitiesRequest.SerializeToString,
            atlas__pb2.QueryCapabilitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryCapabilityMd(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robonix.atlas.Atlas/QueryCapabilityMd',
            atlas__pb2.QueryCapabilityMdRequest.SerializeToString,
            atlas__pb2.QueryCapabilityMdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConnectCapability(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robonix.atlas.Atlas/ConnectCapability',
            atlas__pb2.ConnectCapabilityRequest.SerializeToString,
            atlas__pb2.ConnectCapabilityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DisconnectCapability(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robonix.atlas.Atlas/DisconnectCapability',
            atlas__pb2.DisconnectCapabilityRequest.SerializeToString,
            atlas__pb2.DisconnectCapabilityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryContract(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robonix.atlas.Atlas/QueryContract',
            atlas__pb2.QueryContractRequest.SerializeToString,
            atlas__pb2.QueryContractResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListContracts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robonix.atlas.Atlas/ListContracts',
            atlas__pb2.ListContractsRequest.SerializeToString,
            atlas__pb2.ListContractsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InspectAtlas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robonix.atlas.Atlas/InspectAtlas',
            atlas__pb2.InspectAtlasRequest.SerializeToString,
            atlas__pb2.InspectAtlasResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
