# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: camera.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'camera.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import sensor_msgs_pb2 as sensor__msgs__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63\x61mera.proto\x12\x0erobonix.camera\x1a\x11sensor_msgs.proto\"Z\n\x04RGBD\x12\'\n\x03rgb\x18\x01 \x01(\x0b\x32\x1a.robonix.sensor_msgs.Image\x12)\n\x05\x64\x65pth\x18\x02 \x01(\x0b\x32\x1a.robonix.sensor_msgs.Image\"\x18\n\x16GetCameraImage_Request\"D\n\x17GetCameraImage_Response\x12)\n\x05image\x18\x01 \x01(\x0b\x32\x1a.robonix.sensor_msgs.Imageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'camera_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RGBD']._serialized_start=51
  _globals['_RGBD']._serialized_end=141
  _globals['_GETCAMERAIMAGE_REQUEST']._serialized_start=143
  _globals['_GETCAMERAIMAGE_REQUEST']._serialized_end=167
  _globals['_GETCAMERAIMAGE_RESPONSE']._serialized_start=169
  _globals['_GETCAMERAIMAGE_RESPONSE']._serialized_end=237
# @@protoc_insertion_point(module_scope)
