# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chassis.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'chassis.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import geometry_msgs_pb2 as geometry__msgs__pb2
import sensor_msgs_pb2 as sensor__msgs__pb2
import std_msgs_pb2 as std__msgs__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rchassis.proto\x12\x0frobonix.chassis\x1a\x13geometry_msgs.proto\x1a\x11sensor_msgs.proto\x1a\x0estd_msgs.proto\"\xb9\x01\n\x0bMoveCommand\x12\x10\n\x08linear_x\x18\x01 \x01(\x01\x12\x10\n\x08linear_y\x18\x02 \x01(\x01\x12\x10\n\x08linear_z\x18\x03 \x01(\x01\x12\x11\n\tangular_x\x18\x04 \x01(\x01\x12\x11\n\tangular_y\x18\x05 \x01(\x01\x12\x11\n\tangular_z\x18\x06 \x01(\x01\x12\x14\n\x0c\x64uration_sec\x18\x07 \x01(\x01\x12\x11\n\tforward_m\x18\x08 \x01(\x01\x12\x12\n\nrotate_deg\x18\t \x01(\x01\"\x84\x02\n\nRobotState\x12(\n\x06header\x18\x01 \x01(\x0b\x32\x18.robonix.std_msgs.Header\x12\x35\n\tbase_pose\x18\x02 \x01(\x0b\x32\".robonix.geometry_msgs.PoseStamped\x12\x34\n\x0bjoint_state\x18\x03 \x01(\x0b\x32\x1f.robonix.sensor_msgs.JointState\x12\x34\n\x08tcp_pose\x18\x04 \x01(\x0b\x32\".robonix.geometry_msgs.PoseStamped\x12\x15\n\rgripper_width\x18\x05 \x01(\x01\x12\x12\n\nis_grasped\x18\x06 \x01(\x08\"K\n\x1a\x45xecuteMoveCommand_Request\x12-\n\x07\x63ommand\x18\x01 \x01(\x0b\x32\x1c.robonix.chassis.MoveCommand\"G\n\x1b\x45xecuteMoveCommand_Response\x12(\n\x06status\x18\x01 \x01(\x0b\x32\x18.robonix.std_msgs.String\"\x17\n\x15GetRobotState_Request\"D\n\x16GetRobotState_Response\x12*\n\x05state\x18\x01 \x01(\x0b\x32\x1b.robonix.chassis.RobotStateb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chassis_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MOVECOMMAND']._serialized_start=91
  _globals['_MOVECOMMAND']._serialized_end=276
  _globals['_ROBOTSTATE']._serialized_start=279
  _globals['_ROBOTSTATE']._serialized_end=539
  _globals['_EXECUTEMOVECOMMAND_REQUEST']._serialized_start=541
  _globals['_EXECUTEMOVECOMMAND_REQUEST']._serialized_end=616
  _globals['_EXECUTEMOVECOMMAND_RESPONSE']._serialized_start=618
  _globals['_EXECUTEMOVECOMMAND_RESPONSE']._serialized_end=689
  _globals['_GETROBOTSTATE_REQUEST']._serialized_start=691
  _globals['_GETROBOTSTATE_REQUEST']._serialized_end=714
  _globals['_GETROBOTSTATE_RESPONSE']._serialized_start=716
  _globals['_GETROBOTSTATE_RESPONSE']._serialized_end=784
# @@protoc_insertion_point(module_scope)
