# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: executor.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'executor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import pilot_pb2 as pilot__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x65xecutor.proto\x12\x10robonix.executor\x1a\x0bpilot.proto\"4\n\rBatchComplete\x12\x0f\n\x07plan_id\x18\x01 \x01(\t\x12\x12\n\nany_failed\x18\x02 \x01(\x08\"\xcb\x01\n\x13\x43\x61pabilityCallEvent\x12\x12\n\nevent_kind\x18\x01 \x01(\r\x12\x38\n\x07started\x18\x02 \x01(\x0b\x32\'.robonix.executor.CapabilityCallStarted\x12\x33\n\x06result\x18\x03 \x01(\x0b\x32#.robonix.pilot.CapabilityCallResult\x12\x31\n\x08\x63omplete\x18\x04 \x01(\x0b\x32\x1f.robonix.executor.BatchComplete\"M\n\x15\x43\x61pabilityCallStarted\x12\x0f\n\x07\x63\x61ll_id\x18\x01 \x01(\t\x12\x0e\n\x06\x63\x61p_id\x18\x02 \x01(\t\x12\x13\n\x0b\x63ontract_id\x18\x03 \x01(\t\"e\n\x0e\x43\x61pabilitySpec\x12\x0e\n\x06\x63\x61p_id\x18\x01 \x01(\t\x12\x13\n\x0b\x63ontract_id\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x19\n\x11input_schema_json\x18\x04 \x01(\t\"4\n\x0f\x45xecute_Request\x12!\n\x04plan\x18\x01 \x01(\x0b\x32\x13.robonix.pilot.Plan\"H\n\x10\x45xecute_Response\x12\x34\n\x05\x65vent\x18\x01 \x01(\x0b\x32%.robonix.executor.CapabilityCallEventb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'executor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BATCHCOMPLETE']._serialized_start=49
  _globals['_BATCHCOMPLETE']._serialized_end=101
  _globals['_CAPABILITYCALLEVENT']._serialized_start=104
  _globals['_CAPABILITYCALLEVENT']._serialized_end=307
  _globals['_CAPABILITYCALLSTARTED']._serialized_start=309
  _globals['_CAPABILITYCALLSTARTED']._serialized_end=386
  _globals['_CAPABILITYSPEC']._serialized_start=388
  _globals['_CAPABILITYSPEC']._serialized_end=489
  _globals['_EXECUTE_REQUEST']._serialized_start=491
  _globals['_EXECUTE_REQUEST']._serialized_end=543
  _globals['_EXECUTE_RESPONSE']._serialized_start=545
  _globals['_EXECUTE_RESPONSE']._serialized_end=617
# @@protoc_insertion_point(module_scope)
