# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: liaison.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'liaison.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import pilot_pb2 as pilot__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rliaison.proto\x12\x0frobonix.liaison\x1a\x0bpilot.proto\"7\n\x12SubmitTask_Request\x12!\n\x04task\x18\x01 \x01(\x0b\x32\x13.robonix.pilot.Task\"?\n\x13SubmitTask_Response\x12(\n\x05\x65vent\x18\x01 \x01(\x0b\x32\x19.robonix.pilot.PilotEventb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'liaison_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SUBMITTASK_REQUEST']._serialized_start=47
  _globals['_SUBMITTASK_REQUEST']._serialized_end=102
  _globals['_SUBMITTASK_RESPONSE']._serialized_start=104
  _globals['_SUBMITTASK_RESPONSE']._serialized_end=167
# @@protoc_insertion_point(module_scope)
