# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lidar.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'lidar.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import sensor_msgs_pb2 as sensor__msgs__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0blidar.proto\x12\rrobonix.lidar\x1a\x11sensor_msgs.proto\"\x16\n\x14GetLaserScan_Request\"E\n\x15GetLaserScan_Response\x12,\n\x04scan\x18\x01 \x01(\x0b\x32\x1e.robonix.sensor_msgs.LaserScanb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lidar_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETLASERSCAN_REQUEST']._serialized_start=49
  _globals['_GETLASERSCAN_REQUEST']._serialized_end=71
  _globals['_GETLASERSCAN_RESPONSE']._serialized_start=73
  _globals['_GETLASERSCAN_RESPONSE']._serialized_end=142
# @@protoc_insertion_point(module_scope)
