# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lifecycle_msgs.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'lifecycle_msgs.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14lifecycle_msgs.proto\x12\x16robonix.lifecycle_msgs\"\"\n\x05State\x12\n\n\x02id\x18\x01 \x01(\r\x12\r\n\x05label\x18\x02 \x01(\t\"\'\n\nTransition\x12\n\n\x02id\x18\x01 \x01(\r\x12\r\n\x05label\x18\x02 \x01(\t\"\xb6\x01\n\x15TransitionDescription\x12\x36\n\ntransition\x18\x01 \x01(\x0b\x32\".robonix.lifecycle_msgs.Transition\x12\x32\n\x0bstart_state\x18\x02 \x01(\x0b\x32\x1d.robonix.lifecycle_msgs.State\x12\x31\n\ngoal_state\x18\x03 \x01(\x0b\x32\x1d.robonix.lifecycle_msgs.State\"\xc3\x01\n\x0fTransitionEvent\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12\x36\n\ntransition\x18\x02 \x01(\x0b\x32\".robonix.lifecycle_msgs.Transition\x12\x32\n\x0bstart_state\x18\x03 \x01(\x0b\x32\x1d.robonix.lifecycle_msgs.State\x12\x31\n\ngoal_state\x18\x04 \x01(\x0b\x32\x1d.robonix.lifecycle_msgs.Stateb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lifecycle_msgs_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATE']._serialized_start=48
  _globals['_STATE']._serialized_end=82
  _globals['_TRANSITION']._serialized_start=84
  _globals['_TRANSITION']._serialized_end=123
  _globals['_TRANSITIONDESCRIPTION']._serialized_start=126
  _globals['_TRANSITIONDESCRIPTION']._serialized_end=308
  _globals['_TRANSITIONEVENT']._serialized_start=311
  _globals['_TRANSITIONEVENT']._serialized_end=506
# @@protoc_insertion_point(module_scope)
