# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lifecycle.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'lifecycle.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0flifecycle.proto\x12\x11robonix.lifecycle\"6\n\x0e\x44river_Request\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\r\x12\x13\n\x0b\x63onfig_json\x18\x02 \x01(\t\";\n\x0f\x44river_Response\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\r\n\x05state\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lifecycle_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DRIVER_REQUEST']._serialized_start=38
  _globals['_DRIVER_REQUEST']._serialized_end=92
  _globals['_DRIVER_RESPONSE']._serialized_start=94
  _globals['_DRIVER_RESPONSE']._serialized_end=153
# @@protoc_insertion_point(module_scope)
