# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nav_msgs.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'nav_msgs.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import builtin_interfaces_pb2 as builtin__interfaces__pb2
import geometry_msgs_pb2 as geometry__msgs__pb2
import std_msgs_pb2 as std__msgs__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0enav_msgs.proto\x12\x10robonix.nav_msgs\x1a\x18\x62uiltin_interfaces.proto\x1a\x13geometry_msgs.proto\x1a\x0estd_msgs.proto\"d\n\x05Goals\x12(\n\x06header\x18\x01 \x01(\x0b\x32\x18.robonix.std_msgs.Header\x12\x31\n\x05goals\x18\x02 \x03(\x0b\x32\".robonix.geometry_msgs.PoseStamped\"\x8b\x01\n\tGridCells\x12(\n\x06header\x18\x01 \x01(\x0b\x32\x18.robonix.std_msgs.Header\x12\x12\n\ncell_width\x18\x02 \x01(\x02\x12\x13\n\x0b\x63\x65ll_height\x18\x03 \x01(\x02\x12+\n\x05\x63\x65lls\x18\x04 \x03(\x0b\x32\x1c.robonix.geometry_msgs.Point\"\xa6\x01\n\x0bMapMetaData\x12\x37\n\rmap_load_time\x18\x01 \x01(\x0b\x32 .robonix.builtin_interfaces.Time\x12\x12\n\nresolution\x18\x02 \x01(\x02\x12\r\n\x05width\x18\x03 \x01(\r\x12\x0e\n\x06height\x18\x04 \x01(\r\x12+\n\x06origin\x18\x05 \x01(\x0b\x32\x1b.robonix.geometry_msgs.Pose\"t\n\rOccupancyGrid\x12(\n\x06header\x18\x01 \x01(\x0b\x32\x18.robonix.std_msgs.Header\x12+\n\x04info\x18\x02 \x01(\x0b\x32\x1d.robonix.nav_msgs.MapMetaData\x12\x0c\n\x04\x64\x61ta\x18\x03 \x03(\x05\"\xc0\x01\n\x08Odometry\x12(\n\x06header\x18\x01 \x01(\x0b\x32\x18.robonix.std_msgs.Header\x12\x16\n\x0e\x63hild_frame_id\x18\x02 \x01(\t\x12\x37\n\x04pose\x18\x03 \x01(\x0b\x32).robonix.geometry_msgs.PoseWithCovariance\x12\x39\n\x05twist\x18\x04 \x01(\x0b\x32*.robonix.geometry_msgs.TwistWithCovariance\"c\n\x04Path\x12(\n\x06header\x18\x01 \x01(\x0b\x32\x18.robonix.std_msgs.Header\x12\x31\n\x05poses\x18\x02 \x03(\x0b\x32\".robonix.geometry_msgs.PoseStampedb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nav_msgs_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GOALS']._serialized_start=99
  _globals['_GOALS']._serialized_end=199
  _globals['_GRIDCELLS']._serialized_start=202
  _globals['_GRIDCELLS']._serialized_end=341
  _globals['_MAPMETADATA']._serialized_start=344
  _globals['_MAPMETADATA']._serialized_end=510
  _globals['_OCCUPANCYGRID']._serialized_start=512
  _globals['_OCCUPANCYGRID']._serialized_end=628
  _globals['_ODOMETRY']._serialized_start=631
  _globals['_ODOMETRY']._serialized_end=823
  _globals['_PATH']._serialized_start=825
  _globals['_PATH']._serialized_end=924
# @@protoc_insertion_point(module_scope)
