# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: navigation.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'navigation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import geometry_msgs_pb2 as geometry__msgs__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10navigation.proto\x12\x12robonix.navigation\x1a\x13geometry_msgs.proto\"3\n\x10NavigationStatus\x12\x0f\n\x07goal_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\"+\n\x18\x43\x61ncelNavigation_Request\x12\x0f\n\x07goal_id\x18\x01 \x01(\t\">\n\x19\x43\x61ncelNavigation_Response\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\".\n\x1bGetNavigationStatus_Request\x12\x0f\n\x07goal_id\x18\x01 \x01(\t\"O\n\x1cGetNavigationStatus_Response\x12\r\n\x05known\x18\x01 \x01(\x08\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x10\n\x08terminal\x18\x03 \x01(\x08\"D\n\x10Navigate_Request\x12\x30\n\x04goal\x18\x01 \x01(\x0b\x32\".robonix.geometry_msgs.PoseStamped\"=\n\x11Navigate_Response\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\x12\x16\n\x0estatus_message\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'navigation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NAVIGATIONSTATUS']._serialized_start=61
  _globals['_NAVIGATIONSTATUS']._serialized_end=112
  _globals['_CANCELNAVIGATION_REQUEST']._serialized_start=114
  _globals['_CANCELNAVIGATION_REQUEST']._serialized_end=157
  _globals['_CANCELNAVIGATION_RESPONSE']._serialized_start=159
  _globals['_CANCELNAVIGATION_RESPONSE']._serialized_end=221
  _globals['_GETNAVIGATIONSTATUS_REQUEST']._serialized_start=223
  _globals['_GETNAVIGATIONSTATUS_REQUEST']._serialized_end=269
  _globals['_GETNAVIGATIONSTATUS_RESPONSE']._serialized_start=271
  _globals['_GETNAVIGATIONSTATUS_RESPONSE']._serialized_end=350
  _globals['_NAVIGATE_REQUEST']._serialized_start=352
  _globals['_NAVIGATE_REQUEST']._serialized_end=420
  _globals['_NAVIGATE_RESPONSE']._serialized_start=422
  _globals['_NAVIGATE_RESPONSE']._serialized_end=483
# @@protoc_insertion_point(module_scope)
