# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: shape_msgs.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'shape_msgs.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import geometry_msgs_pb2 as geometry__msgs__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10shape_msgs.proto\x12\x12robonix.shape_msgs\x1a\x13geometry_msgs.proto\"k\n\x04Mesh\x12\x33\n\ttriangles\x18\x01 \x03(\x0b\x32 .robonix.shape_msgs.MeshTriangle\x12.\n\x08vertices\x18\x02 \x03(\x0b\x32\x1c.robonix.geometry_msgs.Point\"&\n\x0cMeshTriangle\x12\x16\n\x0evertex_indices\x18\x01 \x03(\r\"\x15\n\x05Plane\x12\x0c\n\x04\x63oef\x18\x01 \x03(\x01\"O\n\x0eSolidPrimitive\x12\x0c\n\x04type\x18\x01 \x01(\r\x12/\n\x07polygon\x18\x02 \x01(\x0b\x32\x1e.robonix.geometry_msgs.Polygonb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'shape_msgs_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESH']._serialized_start=61
  _globals['_MESH']._serialized_end=168
  _globals['_MESHTRIANGLE']._serialized_start=170
  _globals['_MESHTRIANGLE']._serialized_end=208
  _globals['_PLANE']._serialized_start=210
  _globals['_PLANE']._serialized_end=231
  _globals['_SOLIDPRIMITIVE']._serialized_start=233
  _globals['_SOLIDPRIMITIVE']._serialized_end=312
# @@protoc_insertion_point(module_scope)
