# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: slam.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'slam.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import geometry_msgs_pb2 as geometry__msgs__pb2
import std_msgs_pb2 as std__msgs__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nslam.proto\x12\x0crobonix.slam\x1a\x13geometry_msgs.proto\x1a\x0estd_msgs.proto\"\xab\x01\n\nSlamStatus\x12(\n\x06header\x18\x01 \x01(\x0b\x32\x18.robonix.std_msgs.Header\x12\x0c\n\x04mode\x18\x02 \x01(\t\x12\x12\n\nodom_alive\x18\x03 \x01(\x08\x12\x0f\n\x07odom_hz\x18\x04 \x01(\x02\x12\x13\n\x0b\x63loud_alive\x18\x05 \x01(\x08\x12\x10\n\x08map_file\x18\x06 \x01(\t\x12\x19\n\x11total_odom_frames\x18\x07 \x01(\x04\"\x17\n\x15GetSlamStatus_Request\"B\n\x16GetSlamStatus_Response\x12(\n\x06status\x18\x01 \x01(\x0b\x32\x18.robonix.slam.SlamStatus\"\x1f\n\x0fLoadMap_Request\x12\x0c\n\x04path\x18\x01 \x01(\t\"4\n\x10LoadMap_Response\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"#\n\x0fSaveMap_Request\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"B\n\x10SaveMap_Response\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0c\n\x04path\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"J\n\x16SetInitialPose_Request\x12\x30\n\x04pose\x18\x01 \x01(\x0b\x32\".robonix.geometry_msgs.PoseStamped\";\n\x17SetInitialPose_Response\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\"\n\x12SwitchMode_Request\x12\x0c\n\x04mode\x18\x01 \x01(\t\"M\n\x13SwitchMode_Response\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x14\n\x0c\x63urrent_mode\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'slam_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SLAMSTATUS']._serialized_start=66
  _globals['_SLAMSTATUS']._serialized_end=237
  _globals['_GETSLAMSTATUS_REQUEST']._serialized_start=239
  _globals['_GETSLAMSTATUS_REQUEST']._serialized_end=262
  _globals['_GETSLAMSTATUS_RESPONSE']._serialized_start=264
  _globals['_GETSLAMSTATUS_RESPONSE']._serialized_end=330
  _globals['_LOADMAP_REQUEST']._serialized_start=332
  _globals['_LOADMAP_REQUEST']._serialized_end=363
  _globals['_LOADMAP_RESPONSE']._serialized_start=365
  _globals['_LOADMAP_RESPONSE']._serialized_end=417
  _globals['_SAVEMAP_REQUEST']._serialized_start=419
  _globals['_SAVEMAP_REQUEST']._serialized_end=454
  _globals['_SAVEMAP_RESPONSE']._serialized_start=456
  _globals['_SAVEMAP_RESPONSE']._serialized_end=522
  _globals['_SETINITIALPOSE_REQUEST']._serialized_start=524
  _globals['_SETINITIALPOSE_REQUEST']._serialized_end=598
  _globals['_SETINITIALPOSE_RESPONSE']._serialized_start=600
  _globals['_SETINITIALPOSE_RESPONSE']._serialized_end=659
  _globals['_SWITCHMODE_REQUEST']._serialized_start=661
  _globals['_SWITCHMODE_REQUEST']._serialized_end=695
  _globals['_SWITCHMODE_RESPONSE']._serialized_start=697
  _globals['_SWITCHMODE_RESPONSE']._serialized_end=774
# @@protoc_insertion_point(module_scope)
