# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: speech.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'speech.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import audio_pb2 as audio__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cspeech.proto\x12\x0erobonix.speech\x1a\x0b\x61udio.proto\"\xb5\x02\n\x0b\x44ialogEvent\x12\x14\n\x0ctimestamp_ns\x18\x01 \x01(\x04\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12\x12\n\nevent_type\x18\x03 \x01(\r\x12+\n\tvad_event\x18\x04 \x01(\x0b\x32\x18.robonix.speech.VadEvent\x12\x0c\n\x04text\x18\x05 \x01(\t\x12\x12\n\nconfidence\x18\x06 \x01(\x02\x12\x10\n\x08language\x18\x07 \x01(\t\x12\x15\n\rresponse_text\x18\x08 \x01(\t\x12.\n\x0b\x61udio_chunk\x18\t \x01(\x0b\x32\x19.robonix.audio.AudioChunk\x12\x31\n\x0c\x64ialog_state\x18\n \x01(\x0b\x32\x1b.robonix.speech.DialogState\x12\r\n\x05\x65rror\x18\x0b \x01(\t\"\xb8\x01\n\rDialogRequest\x12\x10\n\x08language\x18\x01 \x01(\t\x12\x10\n\x08voice_id\x18\x02 \x01(\t\x12\x12\n\nenable_vad\x18\x03 \x01(\x08\x12\x1f\n\x17vad_silence_threshold_s\x18\x04 \x01(\x02\x12\x1c\n\x14vad_energy_threshold\x18\x05 \x01(\x02\x12\x30\n\x0c\x61udio_config\x18\x06 \x01(\x0b\x32\x1a.robonix.audio.AudioConfig\"Q\n\x0b\x44ialogState\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\r\n\x05state\x18\x02 \x01(\r\x12\x10\n\x08language\x18\x03 \x01(\t\x12\r\n\x05\x65rror\x18\x04 \x01(\t\"^\n\x08VadEvent\x12\x14\n\x0ctimestamp_ns\x18\x01 \x01(\x04\x12\x12\n\nevent_type\x18\x02 \x01(\r\x12\x12\n\nconfidence\x18\x03 \x01(\x02\x12\x14\n\x0c\x65nergy_level\x18\x04 \x01(\x02\"m\n\x13StartDialog_Request\x12\x10\n\x08language\x18\x01 \x01(\t\x12\x12\n\nenable_vad\x18\x02 \x01(\x08\x12\x30\n\x0c\x61udio_config\x18\x03 \x01(\x0b\x32\x1a.robonix.audio.AudioConfig\"B\n\x14StartDialog_Response\x12*\n\x05\x65vent\x18\x01 \x01(\x0b\x32\x1b.robonix.speech.DialogEventb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'speech_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DIALOGEVENT']._serialized_start=46
  _globals['_DIALOGEVENT']._serialized_end=355
  _globals['_DIALOGREQUEST']._serialized_start=358
  _globals['_DIALOGREQUEST']._serialized_end=542
  _globals['_DIALOGSTATE']._serialized_start=544
  _globals['_DIALOGSTATE']._serialized_end=625
  _globals['_VADEVENT']._serialized_start=627
  _globals['_VADEVENT']._serialized_end=721
  _globals['_STARTDIALOG_REQUEST']._serialized_start=723
  _globals['_STARTDIALOG_REQUEST']._serialized_end=832
  _globals['_STARTDIALOG_RESPONSE']._serialized_start=834
  _globals['_STARTDIALOG_RESPONSE']._serialized_end=900
# @@protoc_insertion_point(module_scope)
