# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stereo_msgs.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'stereo_msgs.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import sensor_msgs_pb2 as sensor__msgs__pb2
import std_msgs_pb2 as std__msgs__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11stereo_msgs.proto\x12\x13robonix.stereo_msgs\x1a\x11sensor_msgs.proto\x1a\x0estd_msgs.proto\"\xf7\x01\n\x0e\x44isparityImage\x12(\n\x06header\x18\x01 \x01(\x0b\x32\x18.robonix.std_msgs.Header\x12)\n\x05image\x18\x02 \x01(\x0b\x32\x1a.robonix.sensor_msgs.Image\x12\t\n\x01\x66\x18\x03 \x01(\x02\x12\t\n\x01t\x18\x04 \x01(\x02\x12;\n\x0cvalid_window\x18\x05 \x01(\x0b\x32%.robonix.sensor_msgs.RegionOfInterest\x12\x15\n\rmin_disparity\x18\x06 \x01(\x02\x12\x15\n\rmax_disparity\x18\x07 \x01(\x02\x12\x0f\n\x07\x64\x65lta_d\x18\x08 \x01(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stereo_msgs_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DISPARITYIMAGE']._serialized_start=78
  _globals['_DISPARITYIMAGE']._serialized_end=325
# @@protoc_insertion_point(module_scope)
