# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tts.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'tts.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import audio_pb2 as audio__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ttts.proto\x12\x0brobonix.tts\x1a\x0b\x61udio.proto\"|\n\x14SynthesizeAudioChunk\x12(\n\x05\x63hunk\x18\x01 \x01(\x0b\x32\x19.robonix.audio.AudioChunk\x12\x10\n\x08\x65ncoding\x18\x02 \x01(\t\x12\x16\n\x0esample_rate_hz\x18\x03 \x01(\r\x12\x10\n\x08is_final\x18\x04 \x01(\x08\"R\n\x12Synthesize_Request\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x10\n\x08language\x18\x02 \x01(\t\x12\r\n\x05voice\x18\x03 \x01(\t\x12\r\n\x05speed\x18\x04 \x01(\x02\"b\n\x13Synthesize_Response\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\x12\x10\n\x08\x65ncoding\x18\x02 \x01(\t\x12\x16\n\x0esample_rate_hz\x18\x03 \x01(\r\x12\r\n\x05\x65rror\x18\x04 \x01(\t\"\x8a\x01\n\x18SynthesizeStream_Request\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x10\n\x08language\x18\x02 \x01(\t\x12\r\n\x05voice\x18\x03 \x01(\t\x12\r\n\x05speed\x18\x04 \x01(\x02\x12\x30\n\x0c\x61udio_config\x18\x05 \x01(\x0b\x32\x1a.robonix.audio.AudioConfig\"M\n\x19SynthesizeStream_Response\x12\x30\n\x05\x63hunk\x18\x01 \x01(\x0b\x32!.robonix.tts.SynthesizeAudioChunkb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tts_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SYNTHESIZEAUDIOCHUNK']._serialized_start=39
  _globals['_SYNTHESIZEAUDIOCHUNK']._serialized_end=163
  _globals['_SYNTHESIZE_REQUEST']._serialized_start=165
  _globals['_SYNTHESIZE_REQUEST']._serialized_end=247
  _globals['_SYNTHESIZE_RESPONSE']._serialized_start=249
  _globals['_SYNTHESIZE_RESPONSE']._serialized_end=347
  _globals['_SYNTHESIZESTREAM_REQUEST']._serialized_start=350
  _globals['_SYNTHESIZESTREAM_REQUEST']._serialized_end=488
  _globals['_SYNTHESIZESTREAM_RESPONSE']._serialized_start=490
  _globals['_SYNTHESIZESTREAM_RESPONSE']._serialized_end=567
# @@protoc_insertion_point(module_scope)
